# Load all libraries

library(shiny)
library(shinyjs)
library(shinythemes)
library(data.table)
library(R6)
library(quantmod)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(lubridate)
library(purrr)
library(zoo)
library(xts)
library(stats)
library(PerformanceAnalytics)
library(plotly)
library(DT)
library(parallel)
library(rugarch)
library(TTR)
library(forecast)
library(gridExtra)
library(stringr)
library(profvis)
library(Rcpp)

# Source C++ version of apply_risk_management() for execution speed increase
Rcpp::sourceCpp("backtesting_trading_strategies/speedup/apply_risk_management_cpp.cpp")
