# Load all libraries

library(shiny)
library(data.table)
library(R6)
library(quantmod)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(lubridate)
library(purrr)
library(zoo)
library(xts)
library(stats)
library(PerformanceAnalytics)
library(plotly)
library(DT)
library(parallel)
library(rugarch)
library(TTR)
library(forecast)
library(gridExtra)